version: '3.1'

services:
  mysql-zabbix:
    container_name: mysql-zabbix
    hostname: mysql-zabbix
    image: mysql:5.7
    networks:
      - zabbix-network
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    command: ['--character-set-server=utf8', '--collation-server=utf8_bin']

  zabbix-server:
    container_name: zabbix-server
    hostname: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.9
    networks:
      - zabbix-network
    links:
      - mysql-zabbix
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=$DB_SERVER_HOST
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    depends_on:
      - mysql-zabbix

  zabbix-web:
    container_name: zabbix-web
    hostname: zabbix-web
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.9
    networks:
      - zabbix-network
    links:
      - mysql-zabbix
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=$DB_SERVER_HOST
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - PHP_TZ=$PHP_TZ
    depends_on:
      - mysql-zabbix
      - zabbix-server
  
    #  zabbix-agent:
    #container_name: zabbix-agent
    #image: zabbix/zabbix-agent:ubuntu-5.0.9
    #networks:
    #  - network-zabbix
    #restart: always
    #environment:
    #  - ZBX_HOSTNAME='zabbix-server'
    #  - ZBX_SERVER_HOST=$ZBX_SERVER_HOST
    #  - ZBX_SERVER_PORT=$ZBX_SERVER_PORT
    #ports:
    #  - '10050:10050'

networks:
  zabbix-network:
    name: zabbix-network
    driver: bridge

